name: Deploy Cloud Run

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and push image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/server:latest
          service: server
